In [ ]:
import pandas as pd

# save the file path
file_path = './datasets/melb_data.csv'

# read & store the data in a DataFrame
melbourne_data = pd.read_csv(file_path)

# print a summary
melbourne_data.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [4]:
# display column names; might have some missing values
# (some houses for which some variables weren't recorded)
print(f'columns: {melbourne_data.columns}')
# print("before cleaning: ", melbourne_data.count(axis=0))

# removes rows with missing values (NaNs) from a DataFrame
# axis=0 -> drop rows; axis=1 -> drop columns

# `dropna` drops missing/"not available" values
melbourne_data = melbourne_data.dropna(axis=0)

#print("after cleaning: ", melbourne_data.count(axis=0))

columns: Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [5]:
# select the 'prediction' target
y = melbourne_data.Price

# features - columns inputted into our model and later used to make predictions
# In our case, those would be the columns used to determine the home price
# Sometimes, you will use all columns EXCEPT the target as features
melbourne_features = ['Rooms', 'Bathroom', 'Landsize', 'Lattitude', 'Longtitude']

In [6]:
# By convention, this data is called `X`
X = melbourne_data[melbourne_features]
X.describe()

             Rooms     Bathroom      Landsize    Lattitude   Longtitude
count  6196.000000  6196.000000   6196.000000  6196.000000  6196.000000
mean      2.931407     1.576340    471.006940   -37.807904   144.990201
std       0.971079     0.711362    897.449881     0.075850     0.099165
min       1.000000     1.000000      0.000000   -38.164920   144.542370
25%       2.000000     1.000000    152.000000   -37.855438   144.926198
50%       3.000000     1.000000    373.000000   -37.802250   144.995800
75%       4.000000     2.000000    628.000000   -37.758200   145.052700
max       8.000000     8.000000  37000.000000   -37.457090   145.526350

In [11]:
# display entries
print(f"Entries are: \n{X}")

Entries are:
       Rooms  Bathroom  Landsize  Lattitude  Longtitude
1          2       1.0     156.0  -37.80790   144.99340
2          3       2.0     134.0  -37.80930   144.99440
4          4       1.0     120.0  -37.80720   144.99410
6          3       2.0     245.0  -37.80240   144.99930
7          2       1.0     256.0  -37.80600   144.99540
...      ...       ...       ...        ...         ...
12205      3       2.0     972.0  -37.51232   145.13282
12206      3       1.0     179.0  -37.86558   144.90474
12207      1       1.0       0.0  -37.85588   144.89936
12209      2       1.0       0.0  -37.85581   144.99025
12212      6       3.0    1087.0  -37.81038   144.89389

[6196 rows x 5 columns]

In [13]:
from sklearn.tree import DecisionTreeRegressor

# Model definition - specify a number for `random_state` to ensure same results each run.
# You may use any number, and model quality won't depend meaningfully on exactly what value you choose.
melbourne_model = DecisionTreeRegressor(random_state=1)

# Fit the model
melbourne_model.fit(X, y)

DecisionTreeRegressor(random_state=1)

In [ ]:
print("Making predictions for the following 5 houses\n")
# display first 5 entries
# print(X.head())

# Compare the top few predictions to the actual home values (in y) for those same homes. Anything surprising?
print(
    f"\nFirst in-sample home prices prediction are: {melbourne_model.predict(X.head())}"
)

print("Actual target values for those homes:", y.head().tolist())

Making predictions for the following 5 houses


First in-sample home prices prediction are: [1035000. 1465000. 1600000. 1876000. 1636000.]
Actual target values for those homes: [1035000.0, 1465000.0, 1600000.0, 1876000.0, 1636000.0]

In [15]:
# Model Validation - measuring the performance of your model, so you can test and compare alternatives

# Bad Approach - In-sample approach using a single sample to build/train & evaluate the model
from sklearn.metrics import mean_absolute_error
predicted_home_prices = melbourne_model.predict(X)
mean_absolute_error(y, predicted_home_prices)

1115.7467183128902

In [18]:
# The Good/Right Approach
from sklearn.model_selection import train_test_split

# split data into training and validation data, for both features and target
# The split is based on a random number generator. Supplying a numeric value to
# the random_state argument guarantees we get the same split every time we
# run this script

# print(train_test_split(X, y, random_state=0))
train_X, val_X, train_y, val_y = train_test_split(X, y, random_state=0)

print("total count X: ", len(X))
print("total count y: ", len(y))
print("train X count: ", len(train_X))
print("test X count: ", len(val_X))
print("train y count: ", len(train_y))
print("test y count: ", len(val_y))

# model definition
model_def = DecisionTreeRegressor(random_state=1)

# fit model
model_def.fit(train_X, train_y)

# display pridicted price on validation data
predicted_prices = model_def.predict(val_X)
print(f"mean absolute error: {mean_absolute_error(val_y, predicted_prices)}")

total count X:  6196
total count y:  6196
train X count:  4647
test X count:  1549
train y count:  4647
test y count:  1549
mean absolute error: 273518.01872175594

In [19]:
# Overfitting and Underfitting
# Fine-tuning your model for better performance.
def get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y):
    model = DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes, random_state=1)
    model.fit(train_X, train_y)
    predicted_value = model.predict(val_X)
    mae = mean_absolute_error(val_y, predicted_value)
    return (mae)

In [20]:
# compare MAE with differing values of max_leaf_nodes
candidate_max_leaf_nodes = [5, 50, 500, 5000]

for max_leaf_node in candidate_max_leaf_nodes:
    val = get_mae(max_leaf_node, train_X, val_X, train_y, val_y)
    print(f"Max leaf nodes: {max_leaf_node}  \t\t Mean Absolute Error:  {val:.0f}")

# shorter/cleaner approach
scores = {
   leaf_size: get_mae(leaf_size, train_X, val_X, train_y, val_y) for leaf_size in candidate_max_leaf_nodes
}

print(f'scores: {scores}')

best_tree_size = min(scores, key=scores.get)

# Of the options listed, 500 is the optimal number of leaves.
print(f'best tree size: {best_tree_size}')

Max leaf nodes: 5  		 Mean Absolute Error:  385697
Max leaf nodes: 50  		 Mean Absolute Error:  279795
Max leaf nodes: 500  		 Mean Absolute Error:  260235
Max leaf nodes: 5000  		 Mean Absolute Error:  273581
scores: {5: 385696.54278937966, 50: 279794.61143891385, 500: 260235.05178963946, 5000: 273580.7566171724}
best tree size: 500

In [22]:
# final model
final_model = DecisionTreeRegressor(max_leaf_nodes=best_tree_size, random_state=1)
final_model.fit(X, y)

DecisionTreeRegressor(max_leaf_nodes=500, random_state=1)

In [41]:
# Optimisation - using a Random Forest
from sklearn.ensemble import RandomForestRegressor

forest_model = RandomForestRegressor(random_state=1)
forest_model.fit(train_X, train_y)
melb_preds = forest_model.predict(val_X)
print(mean_absolute_error(val_y, melb_preds))

207226.35743972045